# Colors (Solarized Light)

# Default colors
[colors.primary]
background = '#fdf6e3'
foreground = '#586e75'

# Normal colors
[colors.normal]
black = '#073642'
red = '#dc322f'
green = '#859900'
yellow = '#b58900'
blue = '#268bd2'
magenta = '#d33682'
cyan = '#2aa198'
white = '#eee8d5'

# Bright colors
[colors.bright]
black = '#002b36'
red = '#dc322f'
green = '#859900'
yellow = '#b58900'
blue = '#268bd2'
magenta = '#d33682'
cyan = '#2aa198'
white = '#fdf6e3'
